// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZidNTolfccx1ttdeE2Z00kfPFMzNGLw',
    appId: '1:1091479524151:web:726b7e9fb226ac1beb80b2',
    messagingSenderId: '1091479524151',
    projectId: 'localservieceapp',
    authDomain: 'localservieceapp.firebaseapp.com',
    storageBucket: 'localservieceapp.firebasestorage.app',
    measurementId: 'G-L1DWNS7HX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9zrTqxESb_0jkA1qp47A0NhVN71yo-8',
    appId: '1:1091479524151:android:72fbf3593bdd88f5eb80b2',
    messagingSenderId: '1091479524151',
    projectId: 'localservieceapp',
    storageBucket: 'localservieceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA5eHvU-GA6NF_3MCxIRmrWYqs0NnoQAw',
    appId: '1:1091479524151:ios:17f2842af93864eceb80b2',
    messagingSenderId: '1091479524151',
    projectId: 'localservieceapp',
    storageBucket: 'localservieceapp.firebasestorage.app',
    iosClientId: '1091479524151-5f91o4fkommj9emvkjiuo4bimaj59uau.apps.googleusercontent.com',
    iosBundleId: 'com.example.localServieceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA5eHvU-GA6NF_3MCxIRmrWYqs0NnoQAw',
    appId: '1:1091479524151:ios:17f2842af93864eceb80b2',
    messagingSenderId: '1091479524151',
    projectId: 'localservieceapp',
    storageBucket: 'localservieceapp.firebasestorage.app',
    iosClientId: '1091479524151-5f91o4fkommj9emvkjiuo4bimaj59uau.apps.googleusercontent.com',
    iosBundleId: 'com.example.localServieceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBZidNTolfccx1ttdeE2Z00kfPFMzNGLw',
    appId: '1:1091479524151:web:af749e43d76999eaeb80b2',
    messagingSenderId: '1091479524151',
    projectId: 'localservieceapp',
    authDomain: 'localservieceapp.firebaseapp.com',
    storageBucket: 'localservieceapp.firebasestorage.app',
    measurementId: 'G-9FLTQ3X479',
  );
}
